"""create table

Revision ID: baa40d6f303b
Revises: 25abd6afc034
Create Date: 2024-07-22 18:04:29.416115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa40d6f303b'
down_revision: Union[str, None] = '25abd6afc034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('profit', sa.String(), nullable=False),
    sa.Column('tax', sa.String(), nullable=False),
    sa.Column('cess', sa.String(), nullable=False),
    sa.Column('total_tax', sa.String(), nullable=False),
    sa.Column('profit_after_tax', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expense', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('value_date', sa.String(), nullable=True),
    sa.Column('transaction_date', sa.String(), nullable=True),
    sa.Column('transaction_posted_date', sa.String(), nullable=True),
    sa.Column('cheque_no_ref_no', sa.String(), nullable=True),
    sa.Column('transaction_remarks', sa.String(), nullable=True),
    sa.Column('withdrawal_amt', sa.String(), nullable=True),
    sa.Column('deposit_amt', sa.String(), nullable=True),
    sa.Column('balance', sa.String(), nullable=True),
    sa.Column('expenses', sa.String(), nullable=True),
    sa.Column('invoices_pdf', sa.LargeBinary(), nullable=True),
    sa.Column('invoices_filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('invoice_pdf', sa.LargeBinary(), nullable=False),
    sa.Column('invoice_filename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('finance')
    op.drop_table('expenses')
    op.drop_table('calculation')
    # ### end Alembic commands ###
